### ISSUE TITLE
How to find a POI ID

### ISSUE THREAD

**Issue by jan-rivo** [MazeMap/URL-API#1]
Hi.
I want to use the API for MazeMap, but I can't figure out how to find the POI ID for a room. Is there an easy way to do this that I have missed?

**Comment by dagjomar** [comment]
If you can search for the POI, try to use the "share menu" and look at the URL. It should display the POI ID

![screenshot 2015-01-29 11 31 48](https://cloud.githubusercontent.com/assets/416408/5956167/c50ca014-a7aa-11e4-913b-51c1934f08ac.png)

**Comment by jan-rivo** [comment]
Thanks!
